### ISSUE TITLE
support via piping in from kubectl get?

### ISSUE THREAD

**Issue by ahmetb** [Kyrremann/kubeflow-eksporter#1]
It seems like `kubectl get pod -o=yaml NAME | kubectl eksporter` is not supported. Is this on the roadmap?

**Comment by Kyrremann** [comment]
I haven't thought about that at all. Why would you do that instead of `kubectl eksporter pod NAME`?

**Comment by ahmetb** [comment]
More natural. Also get has better options like --filter, --all-namespaces. 

I could be also doing something like:

    kubectl get -o=yaml .. | kubectl sort-manifests | kubectl eksporter

**Comment by Kyrremann** [comment]
Good idea! I'll take a crack at it.
